export type StillCostHuntedDTO = {
  Id: string;
  CDIGO: string;
  SEUCDIGO: string;
  NOME: string;
  Nome: string;
  COR: string;
  PESO: string;
  Peso: string;
  ML: string;
  CUSTOKGML: string;
  VlrCusto: string;
  VLRCUSTO: string;
  VLRVENDA: string;
  Diferena: string;
  DIFERENA: string;
  VlrTrat: string;
  VLRTRAT: string;
  MLSobra: string;
  MLSucata: string;
  PesoSobra: string;
  PesoSucata: string;
  VlrSobra: string;
  VlrSucata: string;
  QTBARRAS: string;
  VlrCustoTrat: string;
};
