import { BudgetHunterDTO } from "dtos/BudgetHunterDTO";

const budgetJson = [
  {
    "": "- Selecione uma ação -\nCancelar\nApontamento Produção\nPesquisa de Satisfação\nImprimir\nDuplicar Orçamento\nHistórico\nGarantias do Orçamento\nContratos / Aditivos",
    NroOrc: "992",
    Situao: "ORÇAMENTO",
    Licena: "4448",
    NomeRazoSocial: "LAIS ALVES",
    Vlr: "599,88",
    Vendedor: "CRISTIANE GOMES",
    VlrFaturado: "0,00",
    SaldoFaturar: "599,88",
    DtCadastro: "09/02/2023",
    DtPrevEntrega: "  /  /    ",
    Cliente: "3483465",
    Fone: "",
    Celular: "(66)99932-8908",
    NoPedTemp: "0",
    Fone2: "",
    Endereco: "S/CEP",
    NroCasa: "S/N",
    Bairro: "S/BAIRRO",
    UF: "MT",
    Cidade: "PRIMAVERA DO LESTE",
    CodRef: "",
    ConfiTemp: "TodosNão EnviadoAguardando ConfirmaçãoConfirmadoNão Enviado",
    DtVenda: "/ /",
    DtFatur: "/ /",
    Email: "",
    EstagioProduo: "",
    DtProd: "  /  /     00:00",
    DtRetorno: "  /  /    ",
    NomeTempera: "GUAPORÉ RONDONÓPOLIS - BLINDEX",
    DtConfCliente: "  /  /     00:00",
    ResponsavelObra: "",
    OramentoObraNome: "",
    EnvioTemp: "  /  /     00:00",
    UsuarioEnvio: "",
    Loja: "",
    OrcOriginal: "0",
    Arquiteto: "",
    DescMarkup: "",
    MarkupTotal: "0,00",
    DtAlterado: "09/02/2023",
    Calculado: "",
    Usuario: "CRISTIANE GOMES",
    ErronoClculo: "",
    TEMNFe: "SimNãoNão",
    CdNF: "0",
    Comisso: "0,00",
    SimCompAcess: "0",
    DtPrevAcess: "  /  /    ",
    SimCompPerf: "0",
    DtPrevPerfil: "  /  /    ",
    DataCancelado: "  /  /    ",
    MotivoCancelamento: "",
    MotivodeCancelamento: "",
    CatlogoAtualizado: "",
    Entregueem: "  /  /    ",
    DtAprovaoCliente: "  /  /    ",
    DtGarantiaPerfis: "  /  /    ",
    DtGarantiaAcessorios: "  /  /    ",
    DtGarantiaServios: "  /  /    ",
    DtGarantiaVidro: "  /  /    ",
    ClienteComoConheceuId: "0",
    ClienteCodigo: "902",
    DtAgendaInst: "  /  /    ",
    AgendaDtFinaliz: "  /  /     00:00",
    ComoConheceu: "",
    Recusado: "",
    link: "https://sistema.wvetro.com.br/wvetro/app.wvetro.detalheorcamento?WoaIelBEGWspnTlN_cLSlRmTlTeEbmldzZuyrUa8VWZeFjEYS_XqI09t9i6rtTBx",
  },
  {
    "": "- Selecione uma ação -\nCancelar\nApontamento Produção\nPesquisa de Satisfação\nImprimir\nDuplicar Orçamento\nEmitir Nota fiscal\nHistórico\nGarantias do Orçamento\nContratos / Aditivos",
    NroOrc: "991",
    Situao: "ORÇAMENTO",
    Licena: "4448",
    NomeRazoSocial: "MARCIO VINICIUS",
    Vlr: "47.088,57",
    Vendedor: "ADRIANA R. LEÃO",
    VlrFaturado: "0,00",
    SaldoFaturar: "47.088,57",
    DtCadastro: "08/02/2023",
    DtPrevEntrega: "  /  /    ",
    Cliente: "3476343",
    Fone: "",
    Celular: "(65)9613-1899",
    NoPedTemp: "0",
    Fone2: "",
    Endereco: "",
    NroCasa: "S/N",
    Bairro: "",
    UF: "MT",
    Cidade: "RONDONOPOLIS",
    CodRef: "",
    ConfiTemp: "TodosNão EnviadoAguardando ConfirmaçãoConfirmadoNão Enviado",
    DtVenda: "/ /",
    DtFatur: "/ /",
    Email: "",
    EstagioProduo: "",
    DtProd: "  /  /     00:00",
    DtRetorno: "  /  /    ",
    NomeTempera: "",
    DtConfCliente: "  /  /     00:00",
    ResponsavelObra: "",
    OramentoObraNome: "",
    EnvioTemp: "  /  /     00:00",
    UsuarioEnvio: "",
    Loja: "",
    OrcOriginal: "976",
    Arquiteto: "",
    DescMarkup: "",
    MarkupTotal: "0,00",
    DtAlterado: "09/02/2023",
    Calculado: "",
    Usuario: "Adriana Rodrigues",
    ErronoClculo: "",
    TEMNFe: "SimNãoNão",
    CdNF: "0",
    Comisso: "0,00",
    SimCompAcess: "0",
    DtPrevAcess: "  /  /    ",
    SimCompPerf: "0",
    DtPrevPerfil: "  /  /    ",
    DataCancelado: "  /  /    ",
    MotivoCancelamento: "",
    MotivodeCancelamento: "",
    CatlogoAtualizado: "",
    Entregueem: "  /  /    ",
    DtAprovaoCliente: "  /  /    ",
    DtGarantiaPerfis: "  /  /    ",
    DtGarantiaAcessorios: "  /  /    ",
    DtGarantiaServios: "  /  /    ",
    DtGarantiaVidro: "  /  /    ",
    ClienteComoConheceuId: "0",
    ClienteCodigo: "891",
    DtAgendaInst: "  /  /    ",
    AgendaDtFinaliz: "  /  /     00:00",
    ComoConheceu: "",
    Recusado: "",
    link: "https://sistema.wvetro.com.br/wvetro/app.wvetro.detalheorcamento?WoaIelBEGWspnTlN_cLSlRmTlTeEbmldzZuyrUa8VWZjS-ZZcjItUuHO-y1GvDRu",
  },
];

export default new (class BudgetJsonToDomain {
  toDomain(budgets: BudgetHunterDTO[]) {
    return budgets.map((budget) => {
      return {
        shortId: budget.NroOrc,
        license: budget.Licena,
        customer: {
          name: budget.NomeRazoSocial,
          phone: [budget.Fone, budget.Fone2, budget.Celular],
          email: budget.Email,
          address: {
            street: budget.Endereco,
            number: budget.NroCasa,
            neighborhood: budget.Bairro,
            city: budget.Cidade,
            state: budget.UF,
          },
        },
        items: [],
        total: budget.Vlr,
        date: budget.DtCadastro,
        status: budget.Situao,
        salesman: budget.Vendedor,
        link: budget.link,
      };
    });
  }
})();
